id: IEF311118
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-20T09:49:32+00:00'
last_modified: '2022-06-15T13:51:55.687791+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12111
  title: སྲས་ངག་དབང་བཀྲ་ཤིས་ཀྱིས་མཛད་པའི་བསྡུས་གྲྭ། ༼བཀྲ་ཤིས་འཁྱིལ་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CFD8:
      image_group_id: I1KG12142
      title: Volume 1 of sras ngag dbang bkra shis kyis mdzad pa'i bsdus grwa/ (bkra
        shis 'khyil par ma/)
      total_pages: 316
      order: 1
      base_file: CFD8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
